-- FitTrace 动作库种子数据：7 分类 + 26 动作（含完整教程内容）
-- 动作 steps/tips/cautions 为 JSON 字符串数组；muscle_group 取分类 code

-- ========== 动作分类 ==========
INSERT INTO action_category (name, code, sort) VALUES
    ('胸部', 'CHEST', 1),
    ('背部', 'BACK', 2),
    ('腿部', 'LEGS', 3),
    ('肩部', 'SHOULDERS', 4),
    ('手臂', 'ARMS', 5),
    ('核心', 'CORE', 6),
    ('有氧', 'CARDIO', 7);

-- ========== 胸部（5） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'CHEST'), '杠铃卧推', 'CHEST', 'INTERMEDIATE', '杠铃',
 '胸部复合动作之王，主练胸大肌中束，同时刺激三角肌前束与肱三头肌。',
 '["仰卧平凳，双脚踩实地面，肩胛骨后收下沉并贴紧凳面","双手略宽于肩握杠，杠铃位于胸部正上方","缓慢下放杠铃至胸部中段轻触","胸部发力推起至手臂伸直，杠铃回到正上方"]'::jsonb,
 '["推起时呼气，下放时吸气","肘部与躯干保持约 45 度夹角，避免过度外展","肩胛骨全程收紧，不要耸肩"]'::jsonb,
 '["大重量务必找保护者或使用安全杠","不要用腰部弹起杠铃借力","手腕保持中立，不要后折"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CHEST'), '哑铃卧推', 'CHEST', 'INTERMEDIATE', '哑铃',
 '动作幅度比杠铃更大，能更充分拉伸胸大肌，兼顾两侧平衡。',
 '["仰卧平凳，双手各持哑铃置于胸部两侧，肩胛收紧","向上推起哑铃至手臂伸直，两铃靠近但不碰撞","缓慢下放至胸部两侧，感受胸部拉伸","重复动作，结束时膝盖借力收起哑铃"]'::jsonb,
 '["下放过程控制 2-3 秒，节奏比上推慢","手腕保持中立，哑铃与地面平行","结束时先放哑铃到大腿再坐起"]'::jsonb,
 '["不要下放过低，避免肩关节过度后伸","全程腰部不要离凳"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CHEST'), '上斜哑铃卧推', 'CHEST', 'ADVANCED', '哑铃',
 '重点刺激胸大肌上束，改善上胸厚度与轮廓。',
 '["调整斜凳至 30-45 度，仰卧肩胛收紧","坐姿持铃，推起至锁骨上方","下放至胸大肌上束位置，肘部微外展","推起至上胸收缩，顶峰稍停"]'::jsonb,
 '["斜凳角度不宜超过 45 度，否则肩前束代偿","重量比平卧卧推轻 10-20%"]'::jsonb,
 '["角度过大会增加肩关节压力","腰部不要过度挺起借力"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CHEST'), '俯卧撑', 'CHEST', 'BEGINNER', '徒手',
 '随时随地可练的经典胸肌动作，也是新手学习推类发力模式的入门选择。',
 '["双手略宽于肩撑地，手指朝前，身体呈一条直线","屈肘下放身体至胸部接近地面","胸部发力推起至手臂伸直","核心全程收紧，重复动作"]'::jsonb,
 '["核心收紧避免塌腰或撅臀","新手可从跪姿俯卧撑开始，逐步进阶","顶部可稍作停顿，顶峰收缩"]'::jsonb,
 '["手腕不适时改用俯卧撑架或握拳撑地","不要塌腰，避免腰部压力"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CHEST'), '双杠臂屈伸', 'CHEST', 'ADVANCED', '双杠',
 '下胸与肱三头肌的强力复合动作，需要较好的肩部稳定与上肢力量。',
 '["双手撑杠，身体微微前倾，肩膀下沉","屈肘下放身体至上臂与地面平行","胸部发力推起至手臂伸直","控制下放节奏，重复动作"]'::jsonb,
 '["身体前倾侧重胸肌，直立侧重三头","下放幅度根据肩部活动度调整"]'::jsonb,
 '["肩部不适者避免过深幅度","全程不要耸肩"]'::jsonb, 1);

-- ========== 背部（5） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'BACK'), '引体向上', 'BACK', 'ADVANCED', '单杠',
 '背部最经典的垂直拉动作，全面刺激背阔肌与二头。',
 '["正握单杠，握距略宽于肩","肩胛下沉后收启动，背阔肌发力将身体拉起","拉起至下巴过杠，顶峰稍停","控制下放至手臂接近伸直"]'::jsonb,
 '["避免借助惯性摆动，动作要慢而稳","无法完成可用弹力带辅助或做离心训练"]'::jsonb,
 '["不要完全放松悬吊，避免肩关节压力","不要耸肩"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'BACK'), '高位下拉', 'BACK', 'INTERMEDIATE', '器械',
 '引体向上的器械替代动作，可调节重量，适合系统训练背阔肌宽度。',
 '["坐姿固定大腿，正握横杠略宽于肩","胸部挺起，背阔肌发力将杠拉至锁骨上方","顶峰稍停，缓慢还原至手臂伸直"]'::jsonb,
 '["想象用肘部向下带杠，而不是用手拉","身体保持直立，避免大幅后仰"]'::jsonb,
 '["不要将杠拉到颈后，肩部压力大","不要借体重前后摆动"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'BACK'), '杠铃划船', 'BACK', 'INTERMEDIATE', '杠铃',
 '背部水平拉的核心动作，增厚背部中下斜方与背阔肌厚度。',
 '["俯身约 45 度，背部平直，双手与肩同宽握杠","背阔肌发力将杠拉向腹部","顶部稍停挤压肩胛骨，缓慢下放"]'::jsonb,
 '["保持背部平直，核心收紧","肘部贴近身体向后拉"]'::jsonb,
 '["避免弓背，有腰部受伤风险","不要用惯性甩杠"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'BACK'), '哑铃单臂划船', 'BACK', 'INTERMEDIATE', '哑铃',
 '单侧背部训练，动作幅度大，能精准刺激背阔肌并纠正左右不平衡。',
 '["单膝跪凳，同侧手支撑凳面","另一手持哑铃自然下垂","背阔肌发力将哑铃拉向髋部","顶部稍停，缓慢下放至手臂伸直"]'::jsonb,
 '["感受背部收缩而非手臂发力","躯干保持稳定，不要旋转"]'::jsonb,
 '["避免腰部旋转代偿"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'BACK'), '坐姿绳索划船', 'BACK', 'BEGINNER', '绳索',
 '新手友好的水平拉动作，重量可控，适合学习肩胛后收的发力模式。',
 '["坐姿双脚踩稳踏板，躯干保持直立","双手握把手，肩胛后收将把手拉向腹部","稍停后缓慢还原至手臂伸直"]'::jsonb,
 '["顶峰时胸部打开，肩胛充分后收","离心阶段控制 2 秒"]'::jsonb,
 '["避免弓背前倾","不要借助腰部前后摆动"]'::jsonb, 1);

-- ========== 腿部（6） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'LEGS'), '深蹲', 'LEGS', 'INTERMEDIATE', '杠铃',
 '下肢训练之王，全面刺激股四头肌、臀肌与腘绳肌，提升全身力量。',
 '["杠铃置于斜方肌上，双脚与肩同宽、脚尖微外展","屈髋屈膝下蹲至大腿与地面平行或更低","脚跟发力站起至完全直立"]'::jsonb,
 '["全程保持脊柱中立，核心收紧","膝盖与脚尖方向一致"]'::jsonb,
 '["避免膝盖内扣","大重量务必使用深蹲架安全杠"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'LEGS'), '哑铃高脚杯深蹲', 'LEGS', 'BEGINNER', '哑铃',
 '学习深蹲模式的最佳入门动作，对脊柱压力小。',
 '["双手捧住哑铃置于胸前，肘部朝下","脚跟踩实，下蹲至大腿与地面平行","臀部与大腿发力站起"]'::jsonb,
 '["新手练习深蹲模式的首选","下蹲时膝盖与脚尖同向"]'::jsonb,
 '["保持躯干直立，避免过度前倾"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'LEGS'), '罗马尼亚硬拉', 'LEGS', 'ADVANCED', '杠铃',
 '主练腘绳肌与臀部，是改善后链力量和体态的关键动作。',
 '["双手与肩同宽握杠，膝盖微屈，背部平直","髋部向后移动，杠铃沿大腿下滑至小腿中部","腘绳肌与臀部发力伸髋站直"]'::jsonb,
 '["想象用臀部去关身后的门","杠铃全程贴腿下滑"]'::jsonb,
 '["避免弓背圆腰","下放深度以背部平直为前提"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'LEGS'), '腿举', 'LEGS', 'BEGINNER', '器械',
 '固定轨迹的腿部复合动作，安全系数高，可上较大重量。',
 '["坐入器械，双脚与肩同宽踩踏板，腰部贴紧靠背","解锁后缓慢下放至膝盖约 90 度","脚跟发力推回，膝盖不完全锁死"]'::jsonb,
 '["双脚偏高练臀腿、偏低练股四头","全程保持腰部贴紧靠背"]'::jsonb,
 '["不要锁死膝盖","不要下放过深导致腰部离座"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'LEGS'), '箭步蹲', 'LEGS', 'INTERMEDIATE', '哑铃',
 '单腿训练动作，提升平衡与稳定性，均衡刺激两侧腿臀。',
 '["双手持哑铃于体侧，自然站立","向前迈出一大步下蹲至双膝约 90 度","前脚发力站起，两腿交替进行"]'::jsonb,
 '["前脚膝盖与脚尖同向，不要过度前伸","躯干保持直立，核心收紧"]'::jsonb,
 '["注意平衡，可原地箭步蹲替代行进式"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'LEGS'), '提踵', 'LEGS', 'BEGINNER', '器械',
 '针对小腿三头肌的孤立动作，改善小腿线条。',
 '["前脚掌踩踏板，脚跟悬空，肩部顶住垫子","小腿发力将脚跟抬至最高点","顶峰稍停，缓慢下放至充分拉伸"]'::jsonb,
 '["选择能完成 12-15 次的重量","下放过程感受小腿拉伸"]'::jsonb,
 '["避免弹震式发力，动作要匀速"]'::jsonb, 1);

-- ========== 肩部（4） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'SHOULDERS'), '坐姿哑铃推举', 'SHOULDERS', 'INTERMEDIATE', '哑铃',
 '主练三角肌前束与中束，是肩部体积的核心动作。',
 '["坐姿背部贴紧靠背，哑铃举至肩高、掌心朝前","垂直向上推起至手臂伸直","缓慢下放至肩高位置"]'::jsonb,
 '["保持腰椎中立，避免过度挺腰","下放至耳侧高度即可"]'::jsonb,
 '["不要耸肩","重量过大时腰部会代偿"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'SHOULDERS'), '哑铃侧平举', 'SHOULDERS', 'BEGINNER', '哑铃',
 '三角肌中束的孤立动作，决定肩部宽度。',
 '["双手持铃自然下垂，肘部微屈","向两侧抬起至上臂与肩同高","稍停后缓慢下放"]'::jsonb,
 '["小重量高次数（12-15 次）效果更好","想象用肘部带动抬起"]'::jsonb,
 '["避免耸肩借力","不要摆动甩起"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'SHOULDERS'), '哑铃前平举', 'SHOULDERS', 'INTERMEDIATE', '哑铃',
 '三角肌前束孤立动作，改善肩部整体饱满度。',
 '["双手持铃于大腿前侧，掌心朝后","向前抬至与肩同高","缓慢下放至起始位置"]'::jsonb,
 '["保持躯干稳定，避免后仰借力","可交替进行减少腰部负担"]'::jsonb,
 '["肩部疼痛者适当减重"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'SHOULDERS'), '俯身哑铃飞鸟', 'SHOULDERS', 'INTERMEDIATE', '哑铃',
 '三角肌后束的孤立动作，改善圆肩体态与肩部立体感。',
 '["俯身约 45 度，背部平直，双手持铃自然下垂","向两侧打开至上臂与背部平齐","稍停后缓慢下放"]'::jsonb,
 '["想象抱一棵大树的感觉","肘部微屈并固定角度"]'::jsonb,
 '["不要用惯性甩起","重量过大动作会变形为划船"]'::jsonb, 1);

-- ========== 手臂（4） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'ARMS'), '杠铃弯举', 'ARMS', 'BEGINNER', '杠铃',
 '肱二头肌的基础动作，简单直接，适合建立弯举发力感。',
 '["双手反握杠铃与肩同宽，大臂贴紧身体","屈肘将杠铃弯举至胸前","缓慢下放至手臂伸直"]'::jsonb,
 '["身体保持稳定不晃动","下放阶段控制 2 秒"]'::jsonb,
 '["避免身体后仰借力","手腕保持中立"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'ARMS'), '哑铃锤式弯举', 'ARMS', 'INTERMEDIATE', '哑铃',
 '中立握法的弯举，对腕关节更友好，兼顾肱桡肌。',
 '["双手持铃，掌心相对（中立握）","屈肘弯举至胸前","缓慢下放至手臂伸直"]'::jsonb,
 '["中立握对肱桡肌刺激更大","手腕不适者的弯举首选"]'::jsonb,
 '["避免甩动借力"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'ARMS'), '绳索下压', 'ARMS', 'BEGINNER', '绳索',
 '肱三头肌的孤立动作，恒定张力，刺激感极佳。',
 '["面对器械，双手握绳索两端，大臂夹紧身体","前臂向下压至手臂伸直","稍停后缓慢还原"]'::jsonb,
 '["肘部固定不动，只有前臂运动","顶峰时可稍外旋刺激三头外侧"]'::jsonb,
 '["避免身体前倾借力","不要耸肩"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'ARMS'), '仰卧杠铃臂屈伸', 'ARMS', 'ADVANCED', '杠铃',
 '经典的肱三头肌自由重量动作，对三头整体刺激强烈。',
 '["仰卧平凳，双手窄握杠铃举于胸部上方","大臂固定垂直地面，屈肘将杠铃下放至额头上方","肱三头肌发力伸直手臂"]'::jsonb,
 '["大臂保持垂直地面不动","重量循序渐进"]'::jsonb,
 '["此动作对肘部压力较大，不适即停","务必有保护者"]'::jsonb, 1);

-- ========== 核心（4） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'CORE'), '平板支撑', 'CORE', 'BEGINNER', '徒手',
 '等长核心训练，强化腹横肌与整体躯干稳定。',
 '["前臂撑地，肘部在肩部正下方","身体呈一条直线，收紧核心与臀部","保持 30-60 秒，自然呼吸"]'::jsonb,
 '["臀部不要抬太高或塌腰","质量优先，时间其次"]'::jsonb,
 '["腰部不适者减少时长","肩部不适可改高平板"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CORE'), '卷腹', 'CORE', 'BEGINNER', '徒手',
 '针对腹直肌上段的经典动作，比仰卧起坐更安全。',
 '["仰卧屈膝，双手轻扶耳侧","腹肌发力将肩胛卷离地面","顶部收缩 1 秒，缓慢下放"]'::jsonb,
 '["腰部始终贴地","呼气时卷起，吸气时下放"]'::jsonb,
 '["不要用手拉扯颈部"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CORE'), '俄罗斯转体', 'CORE', 'INTERMEDIATE', '徒手',
 '腹斜肌与旋转稳定的核心训练。',
 '["坐姿屈膝，上身后仰约 45 度","双手合十，躯干左右旋转","两侧交替进行"]'::jsonb,
 '["双脚离地可增加难度","旋转来自胸椎而非腰部"]'::jsonb,
 '["保持背部平直，避免弓背"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CORE'), '悬垂举腿', 'CORE', 'ADVANCED', '单杠',
 '针对腹直肌下段的进阶核心动作，同时考验握力。',
 '["悬垂于单杠，身体稳定不摆动","腹肌发力将双腿抬起至水平或更高","缓慢下放至起始位置"]'::jsonb,
 '["无法完成可先做屈膝举腿","避免用惯性摆动借力"]'::jsonb,
 '["肩部不适者慎做"]'::jsonb, 1);

-- ========== 有氧（2） ==========
INSERT INTO action (category_id, name, muscle_group, difficulty, equipment, description, steps, tips, cautions, status) VALUES
((SELECT id FROM action_category WHERE code = 'CARDIO'), '跑步机慢跑', 'CARDIO', 'BEGINNER', '跑步机',
 '最基础的有氧方式，提升心肺耐力，适合减脂期搭配。',
 '["先快走热身 3-5 分钟","以能说话的速度慢跑 20-40 分钟","结束前降速快走 3-5 分钟放松"]'::jsonb,
 '["保持抬头挺胸，步幅自然","心率控制在最大心率的 60-70%"]'::jsonb,
 '["膝盖不适时减少坡度与时长","不要在跑步机上急停"]'::jsonb, 1),
((SELECT id FROM action_category WHERE code = 'CARDIO'), '动感单车', 'CARDIO', 'BEGINNER', '单车',
 '低冲击有氧训练，对膝盖友好，燃脂效率高。',
 '["调节座位高度，踩至最低点时膝盖微屈","跟随节奏骑行 20-40 分钟","保持匀速与呼吸节奏"]'::jsonb,
 '["阻力适中，保持每分钟 80-100 转","上半身放松，不要耸肩"]'::jsonb,
 '["膝盖疼痛时降低阻力","不要长时间站立骑行"]'::jsonb, 1);
